#! /bin/sh
# Bspwm config
bspc config top_padding 18 #14
bspc config border_width 1
bspc config window_gap 0
bspc config split_ratio 0.50
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Rules
bspc rule -a Steam floating=true follow=false
bspc rule -a ncmpcpp
bspc rule -a Mumble floating=true
bspc rule -a Gimp floating=true
bspc rule -a feh floating=true
bspc rule -a mpv floating=true
bspc rule -a qemu-system-x86_64 floating=true

# Autostart
panel
